package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/kemit/trip-planner/internal/models"
	"gorm.io/gorm"
)

type ChatRepository struct {
	db *gorm.DB
}

func NewChatRepository(db *gorm.DB) *ChatRepository {
	return &ChatRepository{db: db}
}

// CreateSession creates a new chat session
func (r *ChatRepository) CreateSession(session *models.ChatSession) error {
	return r.db.Create(session).Error
}

// FindSessionByID returns a session with all its messages
func (r *ChatRepository) FindSessionByID(id uuid.UUID) (*models.ChatSession, error) {
	var session models.ChatSession
	err := r.db.
		Preload("Messages", func(db *gorm.DB) *gorm.DB {
			return db.Order("created_at ASC")
		}).
		Where("id = ?", id).
		First(&session).Error
	if err != nil {
		return nil, err
	}
	return &session, nil
}

// FindSessionMeta returns a session WITHOUT preloading its messages.
// Used when we only need ownership/metadata (cheaper than FindSessionByID).
func (r *ChatRepository) FindSessionMeta(id uuid.UUID) (*models.ChatSession, error) {
	var session models.ChatSession
	if err := r.db.Where("id = ?", id).First(&session).Error; err != nil {
		return nil, err
	}
	return &session, nil
}

// FindSessionWithMessages returns a session and a paginated slice of its
// messages ordered oldest→newest, plus the total message count.
func (r *ChatRepository) FindSessionWithMessages(id uuid.UUID, page, perPage int) (*models.ChatSession, []models.ChatMessage, int64, error) {
	session, err := r.FindSessionMeta(id)
	if err != nil {
		return nil, nil, 0, err
	}

	var total int64
	r.db.Model(&models.ChatMessage{}).Where("session_id = ?", id).Count(&total)

	var messages []models.ChatMessage
	offset := (page - 1) * perPage
	err = r.db.
		Where("session_id = ?", id).
		Order("created_at ASC").
		Offset(offset).Limit(perPage).
		Find(&messages).Error
	if err != nil {
		return nil, nil, 0, err
	}

	return session, messages, total, nil
}

// RecentMessages returns the newest `limit` messages for a session ordered
// oldest→newest, so it can be fed to the AI as a sliding-context window.
func (r *ChatRepository) RecentMessages(sessionID uuid.UUID, limit int) ([]models.ChatMessage, error) {
	var messages []models.ChatMessage
	err := r.db.
		Where("session_id = ?", sessionID).
		Order("created_at DESC").
		Limit(limit).
		Find(&messages).Error
	if err != nil {
		return nil, err
	}
	// reverse to chronological order
	for i, j := 0, len(messages)-1; i < j; i, j = i+1, j-1 {
		messages[i], messages[j] = messages[j], messages[i]
	}
	return messages, nil
}

// ListSessionsByUserID returns paginated chat sessions for a user (without messages, just metadata)
func (r *ChatRepository) ListSessionsByUserID(userID uuid.UUID, page, perPage int) ([]models.ChatSession, int64, error) {
	var sessions []models.ChatSession
	var total int64

	query := r.db.Model(&models.ChatSession{}).Where("user_id = ?", userID)
	query.Count(&total)

	offset := (page - 1) * perPage
	err := query.
		Offset(offset).Limit(perPage).
		Order("updated_at DESC").
		Find(&sessions).Error

	return sessions, total, err
}

// CreateMessage adds a message to a session and bumps the session's updated_at
// so active conversations rise to the top of the history list.
func (r *ChatRepository) CreateMessage(message *models.ChatMessage) error {
	if err := r.db.Create(message).Error; err != nil {
		return err
	}
	return r.db.Model(&models.ChatSession{}).
		Where("id = ?", message.SessionID).
		Update("updated_at", time.Now()).Error
}

// DeleteSession soft-deletes a chat session. Messages are kept in the table but
// become unreachable because they are only ever loaded through their (now
// soft-deleted) parent session. This keeps the delete strategy consistent
// instead of hard-deleting messages while soft-deleting the session.
func (r *ChatRepository) DeleteSession(id uuid.UUID) error {
	return r.db.Where("id = ?", id).Delete(&models.ChatSession{}).Error
}

// UpdateSessionTitle updates the title of a session. Manual renames also clear
// the auto-generated flag so the AI won't overwrite the user's chosen title.
func (r *ChatRepository) UpdateSessionTitle(id uuid.UUID, title string, autoGenerated bool) error {
	return r.db.Model(&models.ChatSession{}).
		Where("id = ?", id).
		Updates(map[string]interface{}{
			"title":                title,
			"title_auto_generated": autoGenerated,
		}).Error
}

// CountSessionsByUserID returns the total number of chat sessions for a user
func (r *ChatRepository) CountSessionsByUserID(userID uuid.UUID) (int64, error) {
	var count int64
	err := r.db.Model(&models.ChatSession{}).Where("user_id = ?", userID).Count(&count).Error
	return count, err
}
