package services

import (
	"context"
	"errors"
	"fmt"
	"log"
	"strings"

	"github.com/google/uuid"
	"github.com/kemit/trip-planner/internal/models"
	"github.com/kemit/trip-planner/internal/repository"
)

// maxHistoryMessages caps how many prior messages are sent to the AI per turn,
// forming a sliding context window to bound token cost on long conversations.
const maxHistoryMessages = 20

// groundingMaxPlaces caps how many DB places are injected as retrieval context.
const groundingMaxPlaces = 8

type ChatService struct {
	chatRepo       *repository.ChatRepository
	userRepo       *repository.UserRepository
	savedPlaceRepo *repository.SavedPlaceRepository
	placeRepo      *repository.PlaceRepository
	aiClient       *AIClient
}

func NewChatService(
	chatRepo *repository.ChatRepository,
	userRepo *repository.UserRepository,
	savedPlaceRepo *repository.SavedPlaceRepository,
	placeRepo *repository.PlaceRepository,
	aiClient *AIClient,
) *ChatService {
	return &ChatService{
		chatRepo:       chatRepo,
		userRepo:       userRepo,
		savedPlaceRepo: savedPlaceRepo,
		placeRepo:      placeRepo,
		aiClient:       aiClient,
	}
}

type SendMessageInput struct {
	SessionID *uuid.UUID `json:"session_id"`
	Message   string     `json:"message" binding:"required,min=1"`
}

type ChatMessageResponse struct {
	SessionID   uuid.UUID     `json:"session_id"`
	UserMessage MessageDetail `json:"user_message"`
	AIResponse  MessageDetail `json:"ai_response"`
}

type MessageDetail struct {
	ID            uuid.UUID      `json:"id"`
	Role          string         `json:"role"`
	Content       string         `json:"content"`
	IsVerified    bool           `json:"is_verified"`
	RelatedPlaces []RelatedPlace `json:"related_places,omitempty"`
}

// resolveSession loads an existing owned session or creates a new one.
// It returns the session plus whether it was newly created.
func (s *ChatService) resolveSession(userID uuid.UUID, input SendMessageInput) (*models.ChatSession, bool, error) {
	if input.SessionID == nil || *input.SessionID == uuid.Nil {
		session := &models.ChatSession{
			UserID:             userID,
			Title:              truncateString(input.Message, 60),
			TitleAutoGenerated: true,
		}
		if err := s.chatRepo.CreateSession(session); err != nil {
			return nil, false, errors.New("failed to create chat session")
		}
		return session, true, nil
	}

	session, err := s.chatRepo.FindSessionMeta(*input.SessionID)
	if err != nil {
		return nil, false, errors.New("chat session not found")
	}
	if session.UserID != userID {
		return nil, false, errors.New("access denied")
	}
	return session, false, nil
}

// buildHistory returns the sliding-window conversation history for the AI plus
// the user's new message appended.
func (s *ChatService) buildHistory(sessionID uuid.UUID, newMessage string, isNew bool) []ChatHistory {
	var history []ChatHistory
	if !isNew {
		prior, err := s.chatRepo.RecentMessages(sessionID, maxHistoryMessages)
		if err == nil {
			for _, msg := range prior {
				history = append(history, ChatHistory{Role: msg.Role, Content: msg.Content})
			}
		}
	}
	history = append(history, ChatHistory{Role: "user", Content: newMessage})
	return history
}

// buildGrounding performs a lightweight retrieval step: it searches the places
// DB for rows relevant to the user's message and formats them as grounding
// context. This is the read-only "tool" that keeps answers factual.
func (s *ChatService) buildGrounding(message string) string {
	places, err := s.placeRepo.Search(message, groundingMaxPlaces)
	if err != nil || len(places) == 0 {
		return ""
	}
	var b strings.Builder
	for _, p := range places {
		b.WriteString(fmt.Sprintf("ID=%d | %s | city=%s | category=%s | budget=%s | rating=%.1f | %s\n",
			p.ID, p.Name, p.City, p.Category, p.BudgetLevel, p.Rating, truncateString(p.Description, 160)))
	}
	return b.String()
}

// SendMessage sends a user message and returns the AI response (non-streaming).
func (s *ChatService) SendMessage(ctx context.Context, userID uuid.UUID, input SendMessageInput) (*ChatMessageResponse, error) {
	session, isNew, err := s.resolveSession(userID, input)
	if err != nil {
		return nil, err
	}

	history := s.buildHistory(session.ID, input.Message, isNew)

	// Persist the user message.
	userMsg := &models.ChatMessage{
		SessionID: session.ID,
		Role:      "user",
		Content:   input.Message,
	}
	if err := s.chatRepo.CreateMessage(userMsg); err != nil {
		return nil, errors.New("failed to save message")
	}

	aiReq := ChatRequest{
		Message:           input.Message,
		History:           history[:len(history)-1], // history excludes the current msg; prompt carries it
		SystemInstruction: s.buildUserContext(userID).SystemInstruction(),
		Grounding:         s.buildGrounding(input.Message),
	}

	aiResp, err := s.aiClient.AskQuestion(ctx, aiReq)
	if err != nil {
		log.Printf("AI chat error: %v", err)
		aiMsg := &models.ChatMessage{
			SessionID:  session.ID,
			Role:       "assistant",
			Content:    "I'm sorry, I'm currently unable to process your request. Please try again later.",
			IsVerified: false,
		}
		_ = s.chatRepo.CreateMessage(aiMsg)
		return &ChatMessageResponse{
			SessionID:   session.ID,
			UserMessage: toMessageDetail(userMsg, nil),
			AIResponse:  toMessageDetail(aiMsg, nil),
		}, nil
	}

	// Hydrate related places into real records; only keep verified if grounded.
	hydrated := s.hydrateRelatedPlaces(aiResp.RelatedPlaces)
	isVerified := aiResp.IsVerified && len(hydrated) > 0

	aiMsg := &models.ChatMessage{
		SessionID:     session.ID,
		Role:          "assistant",
		Content:       aiResp.Answer,
		IsVerified:    isVerified,
		RelatedPlaces: models.StringSlice(placeIDStrings(hydrated)),
	}
	if err := s.chatRepo.CreateMessage(aiMsg); err != nil {
		return nil, errors.New("failed to save AI response")
	}

	// Auto-title on the first turn if the AI suggested one and the user hasn't
	// manually renamed the session.
	if isNew && session.TitleAutoGenerated && aiResp.SuggestedTitle != "" {
		_ = s.chatRepo.UpdateSessionTitle(session.ID, aiResp.SuggestedTitle, true)
	}

	return &ChatMessageResponse{
		SessionID:   session.ID,
		UserMessage: toMessageDetail(userMsg, nil),
		AIResponse:  toMessageDetail(aiMsg, hydrated),
	}, nil
}

// StreamMessage streams the AI answer. emit is called for each text chunk. When
// the stream finishes the full message is persisted and the saved AI message is
// returned so the handler can send a final event with metadata.
func (s *ChatService) StreamMessage(ctx context.Context, userID uuid.UUID, input SendMessageInput, emit func(string)) (*ChatMessageResponse, error) {
	session, isNew, err := s.resolveSession(userID, input)
	if err != nil {
		return nil, err
	}

	history := s.buildHistory(session.ID, input.Message, isNew)

	userMsg := &models.ChatMessage{
		SessionID: session.ID,
		Role:      "user",
		Content:   input.Message,
	}
	if err := s.chatRepo.CreateMessage(userMsg); err != nil {
		return nil, errors.New("failed to save message")
	}

	aiReq := ChatRequest{
		Message:           input.Message,
		History:           history[:len(history)-1],
		SystemInstruction: s.buildUserContext(userID).SystemInstruction(),
		Grounding:         s.buildGrounding(input.Message),
	}

	full, err := s.aiClient.AskQuestionStream(ctx, aiReq, func(chunk StreamChunk) {
		if chunk.Err == nil && chunk.Text != "" {
			emit(chunk.Text)
		}
	})
	if err != nil && full == "" {
		full = "I'm sorry, I'm currently unable to process your request. Please try again later."
		emit(full)
	}

	aiMsg := &models.ChatMessage{
		SessionID: session.ID,
		Role:      "assistant",
		Content:   full,
	}
	if err := s.chatRepo.CreateMessage(aiMsg); err != nil {
		return nil, errors.New("failed to save AI response")
	}

	if isNew && session.TitleAutoGenerated {
		_ = s.chatRepo.UpdateSessionTitle(session.ID, truncateString(input.Message, 60), true)
	}

	return &ChatMessageResponse{
		SessionID:   session.ID,
		UserMessage: toMessageDetail(userMsg, nil),
		AIResponse:  toMessageDetail(aiMsg, nil),
	}, nil
}

// ListSessions returns paginated chat sessions for a user
func (s *ChatService) ListSessions(userID uuid.UUID, page, perPage int) ([]models.ChatSession, int64, error) {
	if page < 1 {
		page = 1
	}
	if perPage < 1 || perPage > 50 {
		perPage = 10
	}
	return s.chatRepo.ListSessionsByUserID(userID, page, perPage)
}

// GetSession returns a chat session with a paginated slice of its messages.
func (s *ChatService) GetSession(sessionID, userID uuid.UUID, page, perPage int) (*models.ChatSession, []models.ChatMessage, int64, error) {
	if page < 1 {
		page = 1
	}
	if perPage < 1 || perPage > 100 {
		perPage = 50
	}
	session, messages, total, err := s.chatRepo.FindSessionWithMessages(sessionID, page, perPage)
	if err != nil {
		return nil, nil, 0, errors.New("chat session not found")
	}
	if session.UserID != userID {
		return nil, nil, 0, errors.New("access denied")
	}
	return session, messages, total, nil
}

// DeleteSession deletes a chat session
func (s *ChatService) DeleteSession(sessionID, userID uuid.UUID) error {
	session, err := s.chatRepo.FindSessionMeta(sessionID)
	if err != nil {
		return errors.New("chat session not found")
	}
	if session.UserID != userID {
		return errors.New("access denied")
	}
	return s.chatRepo.DeleteSession(sessionID)
}

// RenameSession updates the title of a chat session (manual rename).
func (s *ChatService) RenameSession(sessionID, userID uuid.UUID, title string) error {
	session, err := s.chatRepo.FindSessionMeta(sessionID)
	if err != nil {
		return errors.New("chat session not found")
	}
	if session.UserID != userID {
		return errors.New("access denied")
	}
	// Manual rename clears the auto-generated flag so the AI won't overwrite it.
	return s.chatRepo.UpdateSessionTitle(sessionID, title, false)
}

func toMessageDetail(msg *models.ChatMessage, related []RelatedPlace) MessageDetail {
	return MessageDetail{
		ID:            msg.ID,
		Role:          msg.Role,
		Content:       msg.Content,
		IsVerified:    msg.IsVerified,
		RelatedPlaces: related,
	}
}

// truncateString truncates a string to maxLen runes (UTF-8 safe), appending an
// ellipsis. Safe for multibyte input such as Arabic.
func truncateString(s string, maxLen int) string {
	r := []rune(s)
	if len(r) <= maxLen {
		return s
	}
	if maxLen <= 1 {
		return string(r[:maxLen])
	}
	return string(r[:maxLen-1]) + "…"
}
